name: explicitSNM
version: 0.1.0.0
synopsis: TODO
description: TODO
maintainer:
  - David Quinn Alvarez <dqalombardi@proton.me>
  - Paulius Skaisgiris <paulius.skaisgiris@gmail.com>
  - Djanira dos Santos Gomes <djaniradsgomes@gmail.com>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - containers
  - QuickCheck
  - graphviz
  - hspec
  - smcdel

library:
  source-dirs: lib


tests:
  tests:
    main: tests.hs
    source-dirs: test
    dependencies:
      - explicitSNM
      - QuickCheck
      - hspec
