name: explicitSNM
version: 0.1.0.0
synopsis: TODO
description: TODO
maintainer:
  - Catja Jana Käser catja.kaeser@gmx.ch
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - containers
  - QuickCheck
  - graphviz
  - hspec
  - smcdel
  - matrix
  - vector

library:
  source-dirs: lib


tests:
  tests:
    main: tests.hs
    source-dirs: test
    dependencies:
      - explicitSNM
      - QuickCheck
      - hspec
